package util

import (
	"github.com/google/uuid"

	"file-store/internal/constants"
	"file-store/internal/logger"
	"flag"
	"fmt"
	"strings"
)

type CommandLineArgs struct {
	Id                     string
	Name                   string
	ListenAddress          string
	ApiServerListenAddress string
	BootstrapNodes         []string
	MetadataDBPath         string
	FileStorageBasePath    string
	TestStorage            bool
	LogLevel               logger.LogLevel
}

func ParseCommandLineArgs() CommandLineArgs {
	var (
		id                  string
		name                string
		listenAddress       string
		apiServerAddress    string
		bootstrapNodes      string
		dbPath              string
		fileStorageBasePath string
		testStorage         bool
		logLevel            string
	)

	autoGeneratedUUID := uuid.New().String()

	flag.StringVar(
		&id, "id", autoGeneratedUUID, "ID of the hyperstore node.",
	)
	flag.StringVar(
		&name, "name", constants.DefaultNodeName, "Name of the hyperstore node.",
	)
	flag.StringVar(
		&listenAddress, "listen", constants.DefaultListenAddress,
		"The address the hyperstore server should listen on, in <address:port> notation.",
	)
	flag.StringVar(
		&apiServerAddress, "api-listen", constants.DefaultAPIServerListenAddress,
		"The address the API server should listen on, in <address:port> notation.",
	)
	flag.StringVar(
		&bootstrapNodes, "bootstrap", "",
		"List of bootstrapped nodes in comma separated <address:port> notation.",
	)
	flag.StringVar(
		&dbPath, "db", constants.DbPath, "Path that the metadata DB will be stored in.",
	)
	flag.StringVar(
		&fileStorageBasePath, "file-storage-path", constants.DefaultBaseStorageLocation,
		"Base path that the files will be stored in.",
	)
	flag.BoolVar(
		&testStorage, "test-storage", false,
		"Setting this to true will test the store by storing a sample file.",
	)
	flag.StringVar(
		&logLevel, "log-level", "info",
		"Log level for the application. Syslog compliant levels "+
			"(emergency to trace).",
	)

	flag.Parse()

	var parseId = func() string {
		// TODO: Validate if id is a valid uuid
		return id
	}
	var parseName = func() string {
		// TODO: Validate if name is valid (e.g. no spaces, special characters, etc.)
		return name
	}
	var parseListenAddress = func() string {
		// TODO: Validate if addresses are valid
		return listenAddress
	}
	var parseAPIServerAddress = func() string {
		// TODO: Validate if addresses are valid
		return apiServerAddress
	}
	var parseBootstrapNodes = func() []string {
		// TODO: Validate if addresses are valid
		if bootstrapNodes == "" {
			return make([]string, 0)
		}
		return strings.Split(bootstrapNodes, ",")
	}
	var parseDBPath = func() string {
		// TODO: Validate if path exists
		return dbPath
	}
	var parseFileStorageBasePath = func() string {
		// TODO: Validate if path exists
		if fileStorageBasePath == constants.DefaultBaseStorageLocation {
			basePathPrefix, _ := SafeStringToAddr(listenAddress)
			defaultFileStorageBasePath := fmt.Sprintf(
				"node-%s-%s", basePathPrefix, constants.DefaultBaseStorageLocation,
			)
			return defaultFileStorageBasePath
		}
		return fileStorageBasePath
	}
	var parseTestStorage = func() bool {
		// TODO: Validate if path exists
		return testStorage
	}
	var parseLogLevel = func() logger.LogLevel {
		return logger.GetLogLevelFromStr(logLevel)
	}

	flag.Parse()
	return CommandLineArgs{
		Id:                     parseId(),
		Name:                   parseName(),
		ListenAddress:          parseListenAddress(),
		ApiServerListenAddress: parseAPIServerAddress(),
		BootstrapNodes:         parseBootstrapNodes(),
		MetadataDBPath:         parseDBPath(),
		FileStorageBasePath:    parseFileStorageBasePath(),
		TestStorage:            parseTestStorage(),
		LogLevel:               parseLogLevel(),
	}
}
